package com.edgebee.atlas.ui.controls
{
   import com.edgebee.atlas.ui.UIGlobals;
   import com.edgebee.atlas.ui.containers.Box;
   import com.edgebee.atlas.ui.utils.UIUtils;
   import flash.events.Event;
   import flash.events.MouseEvent;
   
   public class Keypad extends Box
   {
       
      
      private var _textInput:com.edgebee.atlas.ui.controls.TextInput;
      
      private var _shift:Boolean;
      
      private var _layout:Array;
      
      public function Keypad()
      {
         this._layout = [{
            "CLASS":Box,
            "STYLES":{"Gap":2},
            "CHILDREN":[{
               "CLASS":Button,
               "minWidth":30,
               "label":"1",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"2",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"3",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"4",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"5",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"6",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"7",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"8",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"9",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"0",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"Backspace",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onBackspaceClick"
               }]
            }]
         },{
            "CLASS":Box,
            "STYLES":{"Gap":2},
            "CHILDREN":[{
               "CLASS":Button,
               "minWidth":30,
               "label":"Tab",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onTabClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"q",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"w",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"e",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"r",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"t",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"y",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"u",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"i",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"o",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"p",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Spacer,
               "width":32
            }]
         },{
            "CLASS":Box,
            "STYLES":{"Gap":2},
            "CHILDREN":[{
               "CLASS":Spacer,
               "width":64
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"a",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"s",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"d",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"f",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"g",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"h",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"j",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"k",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"l",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"Return",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onReturnClick"
               }]
            }]
         },{
            "CLASS":Box,
            "STYLES":{"Gap":2},
            "CHILDREN":[{
               "CLASS":Button,
               "minWidth":30,
               "label":"Shift",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onShiftClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"z",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"x",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"c",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"v",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"b",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"n",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"m",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onKeyClick"
               }]
            },{
               "CLASS":Button,
               "minWidth":30,
               "label":"Shift",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onShiftClick"
               }]
            }]
         },{
            "CLASS":Box,
            "STYLES":{"Gap":1},
            "CHILDREN":[{
               "CLASS":Button,
               "minWidth":256,
               "label":"Space",
               "STYLES":{
                  "PaddingLeft":6,
                  "PaddingRight":6,
                  "PaddingTop":8,
                  "PaddingBottom":4
               },
               "EVENTS":[{
                  "TYPE":MouseEvent.CLICK,
                  "LISTENER":"onSpaceClick"
               }]
            }]
         }];
         super(Box.VERTICAL);
         horizontalAlign = Box.ALIGN_CENTER;
         setStyle("BackgroundColor",16777215);
         setStyle("BackgroundAlpha",0.45);
         setStyle("CornerRadius",10);
         setStyle("PaddingLeft",5);
         setStyle("PaddingTop",5);
         setStyle("PaddingBottom",5);
         setStyle("PaddingRight",5);
         setStyle("Gap",3);
      }
      
      public function get textInput() : com.edgebee.atlas.ui.controls.TextInput
      {
         return this._textInput;
      }
      
      public function set textInput(param1:com.edgebee.atlas.ui.controls.TextInput) : void
      {
         this._textInput = param1;
      }
      
      override protected function createChildren() : void
      {
         super.createChildren();
         UIUtils.performLayout(this,this,this._layout);
         addEventListener(MouseEvent.CLICK,this.onMouseClick);
         UIGlobals.root.stage.addEventListener(MouseEvent.CLICK,this.onClickOutside,false,0,true);
      }
      
      private function onMouseClick(param1:MouseEvent) : void
      {
         param1.stopPropagation();
      }
      
      private function onClickOutside(param1:MouseEvent) : void
      {
         if(this._textInput)
         {
            dispatchEvent(new Event(Event.COMPLETE));
         }
      }
      
      public function onKeyClick(param1:MouseEvent) : void
      {
         var _loc2_:Button = param1.target as Button;
         if(_loc2_)
         {
            this._textInput.text += _loc2_.label;
            this._textInput.dispatchEvent(new Event(Event.CHANGE));
         }
      }
      
      public function onBackspaceClick(param1:MouseEvent) : void
      {
         if(this._textInput.text.length > 0)
         {
            this._textInput.text = this._textInput.text.slice(0,-1);
            this._textInput.dispatchEvent(new Event(Event.CHANGE));
         }
      }
      
      public function onShiftClick(param1:MouseEvent) : void
      {
         var _loc2_:Box = null;
         var _loc3_:Button = null;
         var _loc5_:uint = 0;
         this._shift = !this._shift;
         var _loc4_:uint = 0;
         while(_loc4_ < numChildren)
         {
            _loc2_ = getChildAt(_loc4_) as Box;
            _loc5_ = 0;
            while(_loc5_ < _loc2_.numChildren)
            {
               _loc3_ = _loc2_.getChildAt(_loc5_) as Button;
               if(Boolean(_loc3_) && Boolean(_loc3_.label.match(/^[a-z]{1,1}$/i)))
               {
                  if(this._shift)
                  {
                     _loc3_.label = _loc3_.label.toLocaleUpperCase();
                  }
                  else
                  {
                     _loc3_.label = _loc3_.label.toLocaleLowerCase();
                  }
               }
               _loc5_++;
            }
            _loc4_++;
         }
      }
      
      public function onSpaceClick(param1:MouseEvent) : void
      {
         this._textInput.text += " ";
         this._textInput.dispatchEvent(new Event(Event.CHANGE));
      }
      
      public function onTabClick(param1:MouseEvent) : void
      {
         this._textInput.text += "\t";
         this._textInput.dispatchEvent(new Event(Event.CHANGE));
      }
      
      public function onReturnClick(param1:MouseEvent) : void
      {
         if(this._textInput.multiline)
         {
            this._textInput.text += "\n";
            this._textInput.dispatchEvent(new Event(Event.CHANGE));
         }
      }
   }
}
